### ISSUE TITLE
Feature suggestion: Compare with an "alternate" field and pass if it matches either field.

### ISSUE THREAD

**Issue by brownbat** [ijgnd/anki__auto_rate_typedin_answer#1]
First, great add on, I really rely on it, especially to help me quickly practice typing Korean.

I have some vocab words with multiple similar definitions, would be amazing if this could advance a card if it matched either the target OR an "Alternate" field.

Might be able to do this by just making a getAlternate() function similar to getOriginal() that just replaces ```self.typeCorrect``` with ```self.card.note()["Alternate"]``` (then later compare that to ```given``` to set ```cond``` to ```True``` if it is).

Not 100% sure that would work out of the box, but might be close.

Anyway, great work either way, thanks for this extension!

**Comment by ijgnd** [comment]
could you update your add-ons and restart Anki. Then you should have the latest version that added a config key "accept_multiple_answers_for_these_notetypes".

Limitation: If you have an error it will always be compared against the field that you have set in "{{type::...}}". 

Does this work for you?

**Comment by brownbat** [comment]
I see the config option and tested with a few cards, but no luck yet.

Tried these two, and named the field based on the settings, then restarted Anki before studying: 
```  "accept_multiple_answers_for_these_notetypes": {
        "HTSK U2 Vocab Recognition": [
            "Alternate Definition"
        ]
```

```  "accept_multiple_answers_for_these_notetypes": {
        "HTSK U2 Vocab Recognition": [
            "Alternate"
        ]
```

I have some debug info on my cards to make sure I'm copy/pasting the names exactly:
```Type of note: HTSK U2 Vocab Recognition
Deck: Korean::Input::Vocab::2-HTSK U2::Lesson 26
Subdeck: Lesson 26
Type of card ("Forward", etc): HTSK Vocab```

**Comment by brownbat** [comment]
Really appreciate you taking this on, thanks. I think this has huge potential to squeeze out just a little more time on reviews.

**Comment by ijgnd** [comment]
The version from this morning only took the *note type* name into account. Based on the debug info you posted you might might have used the *card template name*?

If someone has one note type that generates two different card templates and each of these card templates is a type-in template that should have alternative answer my approach from this morning would be too imprecise. So I just updated the add-on. Now you must set use a nested dictionary/object that contains the note type name and the card template name. For details see the description in the add-on config window.

Does this work now?

**Comment by brownbat** [comment]
Hmm, still coming up with a failure when using the alternate with these settings: 

- Card Type: HTSK Vocab
- Note Type: HTSK U2 Vocab Recognition
- Deck: Korean::Input::Vocab::2-HTSK U2::Lesson 26


```{
    "accept_multiple_answers_for_these_notetypes": {
        "HTSK U2 Vocab Recognition": {
            "HTSK Vocab": [
                "Alternate"
            ]
        }
    },```

**Comment by ijgnd** [comment]
could you update and try again. 

I have add-ons that have more downloads in a day than this one had in a year and I don't really need this. So I didn't invest too much time in this and mostly ~skipped~ outsourced the testing ...

Does it work now?

**Comment by brownbat** [comment]
Sorry for the delay, was bashing my head against CSS weirdness. Works like a charm. Thanks for the patch! Happy to test anytime.
